### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by SupernovaBotDeveloper** [baeriri/multipurpose-bot#2]
Wassup,Im Spaceflight Gaming,I have already told about contribution,if you tell me ur discord tag and username,I can give you moderation commands,My Username- 𝓢𝓹𝓪𝓬𝓮𝓯𝓵𝓲𝓰𝓱𝓽 𝓖𝓪𝓶𝓲𝓷𝓰 (Official)#7337

**Comment by chirari-7** [comment]
just add me in discord (baeri#5439)
