### ISSUE TITLE
webhook message problem

### ISSUE THREAD

**Issue by ghost** [baeriri/multipurpose-bot#4]
Hello i have a problem that is when some webhook sends something the bot sends a error `Invalid user ID in $isBot[845133277769498624] at line 5`  as you can see the picture 
![image](https://user-images.githubusercontent.com/75715847/119075746-f6ed7e00-ba0e-11eb-9971-85f88849cb7a.png) pls fix it

**Comment by chirari-7** [comment]
may i know from what command/code is that?

**Comment by chirari-7** [comment]
i think it's because webhooks aren't bots. just add `$supressErrors` to remove those errors

**Comment by ghost** [comment]
could you pls give me the full code pls

**Comment by chirari-7** [comment]
may i know the command that this error occurred? I'll modify it

**Comment by ghost** [comment]
nothing is changed from your file it is as it is

**Comment by chirari-7** [comment]
haven't changed anything because i don't know. what command it is. but I'll find a solution

**Comment by chirari-7** [comment]
fixed. no more errors
