### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SupernovaBotDeveloper** [baeriri/multipurpose-bot#9]
Yo wassup! I have a suggestion

1) Add YT Notifs
2)Auto Roles
3)Giveaway
4)Moderation

Add these and this will be the best bot in aoi.js

**Comment by avixityyt** [comment]
> Yo wassup! I have a suggestion
> 
> 1. Add YT Notifs
>    2)Auto Roles
>    3)Giveaway
>    4)Moderation
> 
> Add these and this will be the best bot in aoi.js

welll you can contribute it too lol
